// Product-facing strings stay out of layouts so adopters can replace copy without rewriting UI.
export const copy = {
  en: {
    nav: {
      home: "Home",
      models: "Models",
      pricing: "Pricing",
      docs: "Docs",
      status: "Status",
      demo: "Product demo",
    },
    common: {
      openDemo: "Open product demo",
      viewDocs: "Read the setup guide",
      viewModels: "Browse sample models",
      example: "Example data",
      configure: "Configure this starter",
      copy: "Copy",
      copied: "Copied",
      copyFailed: "Copy failed",
      menu: "Open navigation",
      closeMenu: "Close navigation",
      language: "Switch language",
      theme: "Switch color theme",
      skipMain: "Skip to main content",
      primaryNavigation: "Primary navigation",
      repository: "Repository",
      security: "Security",
      brandPolicy: "Brand policy",
      thirdPartyLicenses: "Third-party licenses",
      sampleDisclaimer: "Example content · Not a production service",
    },
    landing: {
      kicker: "React starter · Apache-2.0",
      title: "Ship an AI gateway site without inheriting product-specific baggage.",
      sub: "A reusable marketing, documentation, status, dashboard, and chat-demo foundation. Branding, URLs, content, and demo data are isolated so a new project starts with configuration—not cleanup.",
      metrics: [
        ["1", "central site config"],
        ["5", "crawlable public routes"],
        ["0", "production credentials"],
      ],
      featuresTitle: "A starter with boundaries, not hidden assumptions.",
      features: [
        ["layers", "Separated concerns", "Brand settings, translated content, sample catalog data, and UI components live in distinct modules."],
        ["shield", "Safe demo defaults", "Dashboard and chat examples are labeled, lazy-loaded, and never call a production service."],
        ["book", "Documentation included", "Configuration, architecture, deployment, security, and contribution paths ship with the repository."],
        ["globe", "Real navigation", "Public screens use normal URLs and links so sharing, keyboard use, and search crawling work."],
        ["sun", "Accessible themes", "Light and dark themes share semantic tokens, visible focus states, and reduced-motion behavior."],
        ["bolt", "Modern toolchain", "Vite, React modules, tests, linting, CI, and route-level code splitting replace manual bundles."],
      ],
    },
    footer: {
      summary: "A neutral React foundation for AI gateway products. Replace the sample content before production use.",
      project: "Project",
      resources: "Resources",
      legal: "Legal",
    },
  },
  zh: {
    nav: {
      home: "首页",
      models: "模型",
      pricing: "价格",
      docs: "文档",
      status: "状态",
      demo: "产品演示",
    },
    common: {
      openDemo: "打开产品演示",
      viewDocs: "阅读配置指南",
      viewModels: "查看示例模型",
      example: "示例数据",
      configure: "配置这个 Starter",
      copy: "复制",
      copied: "已复制",
      copyFailed: "复制失败",
      menu: "打开导航",
      closeMenu: "关闭导航",
      language: "切换语言",
      theme: "切换颜色主题",
      skipMain: "跳到主要内容",
      primaryNavigation: "主导航",
      repository: "代码仓库",
      security: "安全策略",
      brandPolicy: "品牌政策",
      thirdPartyLicenses: "第三方许可证",
      sampleDisclaimer: "示例内容 · 非生产服务",
    },
    landing: {
      kicker: "React Starter · Apache-2.0",
      title: "开箱做 AI 网关网站，不再先清理上一套产品的遗留内容。",
      sub: "一套可复用的营销页、文档、状态页、控制台和聊天演示基础。品牌、域名、内容与演示数据彼此分离，新项目从配置开始，而不是从删代码开始。",
      metrics: [
        ["1", "个集中站点配置"],
        ["5", "个可抓取公共路由"],
        ["0", "个生产凭据"],
      ],
      featuresTitle: "提供清晰边界，而不是隐藏假设。",
      features: [
        ["layers", "职责分离", "品牌设置、双语内容、示例目录数据和 UI 组件位于不同模块。"],
        ["shield", "安全演示默认值", "控制台和聊天示例有醒目标识、按路由延迟加载，并且不会调用生产服务。"],
        ["book", "文档随仓库交付", "配置、架构、部署、安全和贡献流程都包含在仓库中。"],
        ["globe", "真实导航", "公共页面使用正常 URL 和链接，支持分享、键盘操作和搜索抓取。"],
        ["sun", "无障碍主题", "深浅主题共用语义化变量，提供可见焦点和 reduced-motion 支持。"],
        ["bolt", "现代工具链", "使用 Vite、React 模块、测试、Lint、CI 和路由分包代替手工拼接。"],
      ],
    },
    footer: {
      summary: "面向 AI 网关产品的中性 React 基础。投入生产前请替换全部示例内容。",
      project: "项目",
      resources: "资源",
      legal: "法律",
    },
  },
};
